### ISSUE TITLE
13-search slide-15

### ISSUE THREAD

**Issue by larryebaum** [chef-training/chef-fundamentals-4.x#100]
Path indicated is missing subdirectory...

Current:~/chef-repo/cookbooks/myhaproxy/default.rb
Should be: ~/chef-repo/cookbooks/myhaproxy/**recipes/**default.rb

**Comment by SteveDelFante** [comment]
This fix should also apply to Slides 11 even though Slide 11 isn't part of a group exercise.

![image](https://cloud.githubusercontent.com/assets/12142968/10462909/2a1b4b1c-7196-11e5-9014-a2ffd5a727c8.png)

**Comment by SteveDelFante** [comment]
Fixed both slides and published v1.0.1 of slides and guides to Box.
