### ISSUE TITLE
Setup Instructions are Incorrect

### ISSUE THREAD

**Issue by burtlo** [chef-training/chef-fundamentals-4.x#27]
<img width="599" alt="screen shot 2015-10-01 at 3 03 43 pm" src="https://cloud.githubusercontent.com/assets/244426/10232409/347a22d2-684e-11e5-904f-f803749e347f.png">

The learner does not have a chef-repo. They will not have a chef-repo until they create a Chef Server account and download a Starter Kit.

**Comment by SteveDelFante** [comment]
Wondering if when the students get to slide 8-10, if I should write that they hold onto the newly-downloaded chefdk-fundamentals-repo for now, and then I should fix the 09-chef-server module to include downloading the starter kit during the Signing Up for a Hosted Chef Account part...and then have them copy the  chefdk-fundamentals-repo cookbooks folder into the chef-repo.

**Comment by burtlo** [comment]
@SteveDelFante wrote:

> @burtlo is "chef generate repo chef-repo" an option or should they download the starter kit?

We could generate a chef-repo. When you generate a chef-repo with the `chef generate repo REPO_NAME` command it does not generate a `.chef` directory. It also creates a number of directories that within there may be confusing to the learner because they are not necessary at the moment.

Right now, I would say no to the `chef generate repo` command. It does not do the necessary thing and it does too much un-necessary things which is a shame as it feels bad not to use a chef tool.

**Comment by burtlo** [comment]
@SteveDelFante I think that they should download the repo zip file, unzip it, and likely rename it to 'chef-repo'. 

In the **Signing Up for a Hosted Chef Account** they download the key and the configuration file as they would normal and you won't have to change a thing.

I updated the https://github.com/chef-training/chefdk-fundamentals-repo to include a `.chef` directory to make it easier for the learner to add the key and configuration file into that directory.

**Comment by reverest66** [comment]
We did not have them download the starter kit.  We really need to have them
do this.

I have not had a chance to read through this entire exchange.  I'm
recovering from a difficult day (ha ha).

Will read through the entire exchange and get back to you.

Thanks!

**Comment by reverest66** [comment]
Okay - I have read through everything.  I agree with Franklin, we don't
want to confuse anything with extra directories.

In my class the week before last, we did download the starter kit, and
things went so much better when we did that.  The big problem, of course,
is that we have them download the repository.  Should we just move that
piece to the hosted chef section?  I think that would make more sense with
the flow we are trying to achieve.

**Comment by burtlo** [comment]
As @reverest66 points out. It is probably easier for the learner to download the starter kit and put the cookbooks directory into the starter kit.

We don't own the starter kit as a deliverable item nor does the team that cares and feeds for it know how we use it. It contains some additional things like the starter cookbook and starter role. So its not ideal. We would be asking people to copy the cookbooks directory over top of the existing cookbook directory. There are situations where that could go wrong.

**Comment by burtlo** [comment]
I have reviewed the Chef Server module and the setup instructions are correct. When someone reviews the Workstation Installation module would you please make sure there are no conflicting instructions.
