### ISSUE TITLE
minor typo on 4-12

### ISSUE THREAD

**Issue by kennonkwok** [chef-training/chef-fundamentals-4.x#30]
line 2 in command box: "mv workstation cookbook" should be "..cookbooks"

**Comment by burtlo** [comment]
Thanks for contributing.

**Comment by SteveDelFante** [comment]
This is strange. My local master says I'm up to date with the github master but my local copy of 4-12 does not show the change. 

$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
