### ISSUE TITLE
Resources Section Docs Slide is different from the Cookbooks Section Docs Slide

### ISSUE THREAD

**Issue by burtlo** [chef-training/chef-fundamentals-4.x#63]
<img width="1194" alt="screen shot 2015-10-04 at 12 54 04 am" src="https://cloud.githubusercontent.com/assets/244426/10266635/a33b5584-6a32-11e5-8cec-721e223edcce.png">

Should we be using the same slide format? Would using a template help?

**Comment by SteveDelFante** [comment]
I think it's fine.
