### ISSUE TITLE
05-testing-cookbooks chef-zero

### ISSUE THREAD

**Issue by SteveDelFante** [chef-training/chef-fundamentals-4.x#65]
Larryebaum reports: Section 05:Slide 15-17, we show chef-zero and refer to this as the 'default' but the .kitchen.yml file generated (and displayed in prior slides) includes chef_solo... we should either have students 'edit' this and/or explain difference between solo and zero...

**Comment by burtlo** [comment]
All the slides I see show 'chef_zero'

![screen shot 2015-10-05 at 9 38 08 am](https://cloud.githubusercontent.com/assets/244426/10283347/d553fab8-6b44-11e5-84f2-383323a020a2.png)

**Comment by burtlo** [comment]
This has been fixed.
