### ISSUE TITLE
Add Instructor Note with "Estimated Completion Time" to all Labs

### ISSUE THREAD

**Issue by burtlo** [chef-training/chef-fundamentals-4.x#68]
```
Instructor Note: Allow X minutes to complete this exercise.
```

- [x] Resources
- [x] Cookbooks
- [x] Chef-Client
- [x] Testing Cookbooks
- [x] Details about the System
- [x] Desired State and Data

- [x] Chef Server
- [x] Community Cookbooks
- [x] Managing Multiple Nodes
- [x] Roles
- [x] Search
- [x] Environments

**Comment by burtlo** [comment]
There are no lab exercises in the Chef Server module

**Comment by SteveDelFante** [comment]
Not slides 9-40 through 9-44?

**Comment by burtlo** [comment]
That's right. I'm in that section now.

**Comment by burtlo** [comment]
All of the sections listed here, to the best of my knowledge, have estimated times for completion.
