### ISSUE TITLE
Inconsolata font causing probelems

### ISSUE THREAD

**Issue by SteveDelFante** [chef-training/chef-fundamentals-4.x#74]
larryebaum: I'm thinking you may be using some non standard fonts. I get warnings when opening docs and orange highlights misaligns  and text often doesn't fit in boxes. Many staff use only the standard fonts installed.
Larry said it is the code font causing problems.

We should use a code font that everyone has, like Courier New.

**Comment by burtlo** [comment]
@larryebaum the font you are looking for to use the presentation is http://www.levien.com/type/myfonts/inconsolata.html.

**Comment by burtlo** [comment]
I'll add the Inconsolata font to the repository. I think that we could package it with the presentation.

**Comment by SteveDelFante** [comment]
Thanks. Brian would rather we don't "require the install of any non standard fonts for our training materials." I will talk to Rebecca and maybe work with her to change them all to Courier, adjusting font size as necessary. @burtlo Please don't let this stop you from finishing your speaker note work through the remaining modules.

**Comment by burtlo** [comment]
Why is this conversation not happening here in the issue or in the slack channel?

**Comment by burtlo** [comment]
This is non-trivial work.
