### ISSUE TITLE
10-community-cookbooks Slide 4 -  need to establish a new node within our organization that applies that cookbook.

### ISSUE THREAD

**Issue by SteveDelFante** [chef-training/chef-fundamentals-4.x#79]
larryebaum: section 10...slide 4 think wording is incorrect...

[3:39 PM] larryebaum: We will need to establish a new node within our organization that applies that cookbook.
NEW MESSAGES

[3:39 PM] larryebaum: Maybe should be "We will need to establish a new node within our organization to which we apply that cookbook."

[3:41 PM] larryebaum: slide 5: delete trailing '/' character...

**Comment by burtlo** [comment]
In the future, if you could please attach a screenshot of the slide in this issue. As the slide numbers associated with the comments here may move making it harder to track down the issue https://github.com/blog/1347-issue-attachments.

**Comment by burtlo** [comment]
<img width="740" alt="screen shot 2015-10-06 at 1 41 03 pm" src="https://cloud.githubusercontent.com/assets/244426/10318616/f3739d32-6c2f-11e5-8e28-c1dca74b38e9.png">


Removed the trailing slash character from the URL.

**Comment by burtlo** [comment]
<img width="741" alt="screen shot 2015-10-06 at 1 47 30 pm" src="https://cloud.githubusercontent.com/assets/244426/10318807/d05d706a-6c30-11e5-8a1b-618ff68a4b53.png">
