### ISSUE TITLE
10-community-cookbooks - slide 23/24: inconsistency... one shows node['haproxy']['members'] = [{, the other the brace is on the following line...

### ISSUE THREAD

**Issue by SteveDelFante** [chef-training/chef-fundamentals-4.x#80]
slide 23/24: inconsistency... one shows node['haproxy']['members'] = [{, the other the brace is on the following line...

**Comment by burtlo** [comment]
In the future would you please include ScreenShots of the slide to make it easier to understand the issue. https://github.com/blog/1347-issue-attachments

**Comment by burtlo** [comment]
Here it shown inline:

<img width="743" alt="screen shot 2015-10-05 at 6 45 27 pm" src="https://cloud.githubusercontent.com/assets/244426/10296745/53d13e90-6b91-11e5-9e27-3b579426bbed.png">

Here it shown on the next line and removed:

<img width="745" alt="screen shot 2015-10-05 at 6 45 34 pm" src="https://cloud.githubusercontent.com/assets/244426/10296755/5ed90ebc-6b91-11e5-9e76-2f7f332393b7.png">
